language: node_js
node_js:
  - "10"
cache:
  npm: true
install:
  - yarn
before_script:
  - git clone --branch master https://github.com/fiteen/fiteen.github.io public
script:
  - hexo cl
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "FiTeen"
  - git config user.email "isfiteen@icloud.com"
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - resource  # 监测源码分支
env:
    global:
        - GH_REF: github.com:fiteen/fiteen.github.io.git